Configurações As screen:
    Fill: =If(dark, RGBA(31, 29, 29, 1), White)

    Label1 As label:
        Color: =RGBA(255, 191, 0, 1)
        Height: =77
        Size: =21
        Text: ="Configurações"
        Width: =227
        X: =232
        Y: =398
        ZIndex: =1

